### ISSUE TITLE
Floating point values are multiplied by some power of 10 (solution: install v4+)

### ISSUE THREAD

**Issue by jstaerk** [molsonkiko/JsonToolsNppPlugin#23]
When I pretty print `{"bookmark":    {    },"globalConfig":    {    "__modelVersion": 2.201	}}`
the output is
```
{
"bookmark":
    {
    },
"globalConfig":
    {
    "__modelVersion": 2201.0
    }
}
```
i.e. the _modelVersion is multiplied by 1000?

**Comment by jstaerk** [comment]
I don't know if that's related but I work in a german locale , we use `.` as thousands delimiter and `,` for decimal separation.

**Comment by molsonkiko** [comment]
Hi @jstaerk , this is a sufficiently common issue that I'm going to pin this and not close it.

Just install any version above [v4.0](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v4.0.0) or whatever the [current latest release](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/latest) is. That should fix the bug.

**Comment by jstaerk** [comment]
seems to work thanks
