### ISSUE TITLE
Pretty print: Unintentinally converts amlauta chars

### ISSUE THREAD

**Issue by Japollack** [molsonkiko/JsonToolsNppPlugin#25]
"Pretty-print current JSON file" command would turn this:
`{
	"cities": [
		"Tallinn",
		"Pärnu",
		"Tartu",
		"Valga",
		"Jõhvi",
		"Haapsalu",
		"Jõgeva",
		"Võru"
	]
}`

into this:
`{
    "cities": [
        "Tallinn",
        "P\u00e4rnu",
        "Tartu",
        "Valga",
        "J\u00f5hvi",
        "Haapsalu",
        "J\u00f5geva",
        "V\u00f5ru"
    ]
}`

Using Json Tools v4.6.1 with Notepad++ v8.4.7.

The JSON file is saved as UTF-8 BOM with Windows line endings.

Remove the .log from the file name: [nppJsonToolUmlautaSample.json.log](https://github.com/molsonkiko/JsonToolsNppPlugin/files/10267395/nppJsonToolUmlautaSample.json.log)

PS. Probably the issue lies here:
https://github.com/molsonkiko/JsonToolsNppPlugin/blob/6519711170de55f3fd2a345d6623e2d18a475430/JsonToolsNppPlugin/JSONTools/JNode.cs#L271

**Comment by molsonkiko** [comment]
Hi Japollack, yes, this was an intentional design decision on my part. That said, I agree that it can make JSON with lots of non-ASCII characters less readable. I'm working on this right now and should have a patch finished in a couple of hours.
