### ISSUE TITLE
When having two panels (views), it pretty-prints the json on the left and not the right regardless of the focus

### ISSUE THREAD

**Issue by urheil** [molsonkiko/JsonToolsNppPlugin#27]
Hi, 

Without "other views" opened, when having a json open, i go
Move Document -> Move to Other View

Now i have to "panels" or "views", one on the left and one in the right.
When focus on the right one, I do:
Plugins/JsonTools/Pretty-print... 

It doesn't work.

But if in that moment i have another json opened in the left panel, it pretty-print the one in the left, always.

**Comment by molsonkiko** [comment]
Hi @urheil , thanks for raising this issue. I've been aware of it for some time, and I've basically coped by not using JsonTools when multiple views or instances are open (yes, the same problem happens with multi-instance). Obviously this is much less than ideal.

I'll see if I can figure out a fix for it.

**Comment by molsonkiko** [comment]
Hi @urheil , I think I've fixed the problem in [the newest release](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v4.9.1).

**Comment by urheil** [comment]
thanks!
