### ISSUE TITLE
Feature request: Put buttons on toolbar

### ISSUE THREAD

**Issue by MDagni** [molsonkiko/JsonToolsNppPlugin#36]
It would be really nice to have buttons for commands on the toolbar. I especially need "Pretty-print current JSON file" and "Path to current line".
Thanks.

**Comment by molsonkiko** [comment]
Seems like a good idea. I generally prefer using the accelerator keys (`Alt-P-J-P` (as a sequence, not holding `Alt` down) for pretty-print and `Alt-P-J-O` for `path to current line`, but I'll add toolbar buttons in the next release.

**Comment by molsonkiko** [comment]
as of next release, should be fixed

**Comment by molsonkiko** [comment]
One thing I've observed in playing around with this is that *sometimes* the icons disappear when going from light mode to dark mode (but not vice versa). This is only temporary; when you restart Notepad++ in dark mode or light mode the icons are all there.

If you or anyone else happen to notice a clear pattern of usage that makes the icons more likely to disappear, please let me know and I'll try to fix it.

**Comment by MDagni** [comment]
How can I test this? Release 5.6 doesn't have the icons.

**Comment by MDagni** [comment]
I believe I will just wait :)

**Comment by molsonkiko** [comment]
[New release with toolbar icons](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v5.7.0) just came out.

**Comment by molsonkiko** [comment]
I'm going to close this, although issue #53 is a known lingering issue with the toolbar icons.
