### ISSUE TITLE
"Pretty-print current JSON file" function problems

### ISSUE THREAD

**Issue by mingditts** [molsonkiko/JsonToolsNppPlugin#40]
Hi,
if you try to pretty-print function on the current text

`{
	"Value": 22.0
}`

you'll get this result:

`{
"Value": 220.0
}`

It changes the value of the decimal "Value" property.
It's correct?
Thank you!

**Comment by molsonkiko** [comment]
Install the latest version, or at least install a version greater than 4.0

I pinnned this issue (`Floating point values are multiplied by some power of 10 (solution: install v4+)`) in the hopes that you would notice that.

**Comment by mingditts** [comment]
Thanks, i checked the updates available for you plugin using the notepad++ plugin manager but no updates found after version 3. The problem was the old version of notepad++ itself. After the update of notepad++ now i see the version 4.14 and the bug was solved. Sorry and thanks!
