### ISSUE TITLE
Status bar constantly reverts to JSON

### ISSUE THREAD

**Issue by vinsworldcom** [molsonkiko/JsonToolsNppPlugin#42]
A little troubleshooting and I think this plugin is causing the issue.

1) Open Notepad++, blank file (new 1) on tab
2) enter the valid JSON `{}`
3) Plugins => JsonTools => Pretty-print current JSON file
4) close the file - when prompted to save, select "No"
5) File => New

Observe the bottom left status bar now shows "JSON" even though Language menu shows the default "None (Normal Text)" is selected as the file type.  Open a close any number of windows and any time a blank window with the "new 1" name is opened, "JSON" shows in the bottom left status bar as the file type.

Can you reproduce this?  Any idea what's causing it?

Cheers.

**Comment by molsonkiko** [comment]
Never noticed this before: good catch!

Yeah, I know exactly what is causing this, and I should be able to fix it
soon.

**Comment by molsonkiko** [comment]
As far as I can tell, this issue has been resolved by the latest commit.

To avoid similar issues in the future, I made a somewhat larger refactor than was strictly necessary. My testing suggests that this shouldn't lead to any new access violations or  other weirdness, but I'm not 100% sure there won't be any going forward.
