### ISSUE TITLE
Change default of "sort_keys" from True to False

### ISSUE THREAD

**Issue by rlwakefield** [molsonkiko/JsonToolsNppPlugin#64]
Whenever I go and install the JSON Tools Notepad++ Plugin on a machine that I hadn't configured before, I always have to remember to go to it's settings and change the "sort_keys" (under the JSON formatting section) from True to False as I don't want to have them sorted alphabetically. So I am hoping that this can be altered to be default to False instead of True.

**Comment by molsonkiko** [comment]
This was changed in version 7.0. I recommend upgrading to [v7.2](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v7.2.0).
