### ISSUE TITLE
jsonTools (pretty print / validation) assumes that you want to always want to validate the text on the left hand side

### ISSUE THREAD

**Issue by robbinmav** [molsonkiko/JsonToolsNppPlugin#76]
version v4.4

steps to reproduce

1. Create a window with a piecer of text - it is important that this is not a piece of JSON
2. Create a new window with a valid piece of JSON - it doesn't matter what it is providing it is valid
3. Click on the tab with the piece of JSON to select the tab
4. Right click on the tab
5. Move Document->Move to other view
6. Select the tab that has been moved. This is important because logically you want to use the plugin on the tab that has been selected
7.  Now perform the pretty print/validation - 
8. Plugin menu->jsonTools->PrettyPrint current JSON file
9. An error is displayed stating that the JSON is not valid. 
This occurs because the jsonTools assumes that you want to perform the operation on the Left Hand Side i.e. the side that doesn't have the JSON text

This is confirmed by moving the tab BACK to the left hand side.
When the tab is moved back and selected then the operation works

**Comment by molsonkiko** [comment]
This was fixed a long time ago. [Upgrade to a newer version](https://github.com/molsonkiko/JsonToolsNppPlugin/releases).
